### PR TITLE
Use original title for movies

### PR DESCRIPTION
**Pull request by jawira**
Hi, since I'm a Spanish speaker, I have many Mexican and Spaniard movies in my collection. When I try to rename my movies, the renaming fails since the English title is suggested.

Here an example for *El laberinto del fauno*:

> $ media-sort El\ laberinto\ del\ fauno.mkv 
2020/05/03 11:43:37 Searching el laberinto del fauno
2020/05/03 11:43:38 [#1/1] El laberinto del fauno.mkv
  └─> No results (closest result was 'Pan's Labyrinth' with an accuracy score of 83)

IMHO it makes no sense to use English title for all the movies, I mean, the movie is in Spanish and was filmed in Spain. This PR fixes this using the *original title* instead.

This change has no effect on English speaking movies (which are vast the majority of movies in this world).

### CODE REVIEW

**Comment by jawira** [comment]
Also, it's easier for Kodi to scrap content when using original title in filenames

**Comment by jawira** [comment]
🦗

**Comment by jpillora** [comment]
Can you make it fallback to Title when OriginalTitle is blank? Then looks okay to merge

**Comment by jawira** [comment]
Hi, can you please double check my code, I'm not a Go expert :)

**Comment by jpillora** [comment]
Looks good, thanks :)

**Pull request merged**
